### ISSUE TITLE
Chaos Magician and Cultist actions resulting in unknown points

### ISSUE THREAD

**Issue by smartshaila** [ryanechternacht/witches-den#4]
In this game:

http://witchesden.echternacht.org/analyze/game/centreville

points associated with the Chaos Magicians' stronghold action and the Cultists' faction-based leech action are being categorized as unknown.

**Comment by ryanechternacht** [comment]
Cultists fixed in v1.0.4 (6f88a1fc1b641a5dab1936fbd5a424092e3b60db)
Chaos Magicians fixed in v1.0.3 (69df2cd47a52baa5080ea0a9f16e885ae04f10b3)
