### ISSUE TITLE
Shapeshifter actions not resolving to points

### ISSUE THREAD

**Issue by smartshaila** [ryanechternacht/witches-den#7]
Points associated with shapeshifter action 'ACTH' are being tagged as unknown:

http://dwitchesden.echternacht.org/analyze/game/Exp11

**Comment by ryanechternacht** [comment]
Try to send me links to the prod site, not the dev one. Although this issue is still an issue in prod.

**Comment by ryanechternacht** [comment]
Upon seeing where I decided to take the site, I'm currently focusing on faction level stats based on league games. Because Fire & Ice components are included in league, this is falling low on the priority list. 

It'll get done when I decide to put more emphasis on Fire & Ice
