### ISSUE TITLE
Incorrect faction colors

### ISSUE THREAD

**Issue by smartshaila** [ryanechternacht/witches-den#8]
Riverwalkers, Shapeshifters, and Ice Maidens are all displaying black text on black bars in the Faction Score Breakdown graphs, while Yetis, Acolytes and Dragonlords are being colored correctly.

Examples:
http://dwitchesden.echternacht.org/analyze/game/hail
http://dwitchesden.echternacht.org/analyze/game/chicago
http://dwitchesden.echternacht.org/analyze/game/Exp11

**Comment by ryanechternacht** [comment]
Fixed Ice Maidens in v1.1.1 (59484bbbe1f64548c156310a7e73c2703af242a0)

Changed Riverwalkers and Shapeshifters to a different color in v1.1.1 (03f8c472c4e35cbcbab6435adbfd28ab9da5a85e)
