### ISSUE TITLE
Variable bar height on Faction Score graph

### ISSUE THREAD

**Issue by smartshaila** [ryanechternacht/witches-den#9]
The bar height on the Faction Score Breakdown graph is dependent on the number of factions in a game making it difficult to read faction names on 5p games.

2p - http://dwitchesden.echternacht.org/analyze/game/carmine
3p - http://dwitchesden.echternacht.org/analyze/game/andromeda
4p - http://dwitchesden.echternacht.org/analyze/game/onion
5p - http://dwitchesden.echternacht.org/analyze/game/benoni06

**Comment by ryanechternacht** [comment]
Fixed in v1.1.1 (ed57e9b90316a57e497515a4565522bba5006fb0)
